apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: my-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  MYSQL_HOST: mysql-k8s-svc
